package com.capstone.dependencyrisk.entity;

public enum AnalysisStatus {
    QUEUED,
    VALIDATING_REPOSITORY,
    FETCHING_REPOSITORY,
    DETECTING_ECOSYSTEM,
    SCANNING_MANIFESTS,
    EXTRACTING_DEPENDENCIES,
    RESOLVING_VERSIONS,
    SECURITY_ANALYSIS,
    COMPATIBILITY_ANALYSIS,
    CALCULATING_RISK,
    OPTIMIZING_BATCHES,
    GENERATING_REPORT,
    COMPLETED,
    FAILED,
    REPOSITORY_NOT_FOUND,
    REPOSITORY_ACCESS_DENIED,
    RATE_LIMITED,
    MANIFEST_NOT_FOUND,
    UNSUPPORTED_ECOSYSTEM,
    SECURITY_DATA_UNAVAILABLE,
    PENDING,
    IN_PROGRESS
}
