package com.capstone.dependencyrisk.analyzer.lockfile;

import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

public class YarnAndPnpmLockParserTest {

    @Test
    public void testYarnLockParser() {
        YarnLockParser parser = new YarnLockParser();
        assertTrue(parser.canHandle("yarn.lock"));

        String yarnLock = "# THIS IS AN AUTOGENERATED FILE.\n" +
                "\"axios@^1.6.0\", \"axios@1.6.0\":\n" +
                "  version \"1.6.7\"\n" +
                "  resolved \"https://registry.yarnpkg.com/axios/-/axios-1.6.7.tgz\"\n" +
                "\n" +
                "\"@angular/core@^17.0.0\":\n" +
                "  version \"17.1.0\"\n";

        Map<String, String> resolved = parser.parseResolvedVersions(yarnLock);
        assertNotNull(resolved);
        assertEquals("1.6.7", resolved.get("axios"));
        assertEquals("17.1.0", resolved.get("@angular/core"));
    }

    @Test
    public void testPnpmLockParser() {
        PnpmLockParser parser = new PnpmLockParser();
        assertTrue(parser.canHandle("pnpm-lock.yaml"));

        String pnpmLock = "lockfileVersion: 5.4\n" +
                "packages:\n" +
                "  /axios@1.6.7:\n" +
                "    resolution: {integrity: sha512-...}\n" +
                "  /@angular/core@17.0.2:\n" +
                "    resolution: {integrity: sha512-...}\n";

        Map<String, String> resolved = parser.parseResolvedVersions(pnpmLock);
        assertNotNull(resolved);
        assertEquals("1.6.7", resolved.get("axios"));
        assertEquals("17.0.2", resolved.get("@angular/core"));
    }
}
